[package]
name = "iup"
version = "0.1.0"
authors = ["mark-summerfield <mark@qtrac.eu>"]
edition = "2018"


[profile.release]
codegen-units = 1
lto = "fat"

[dependencies]
lazy_static = "^1"
libloading = "^0.6"
